# Generated by Django 3.2.8 on 2021-10-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateTimeField(verbose_name='exercise day')),
                ('watched', models.TextField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Pushup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateTimeField(verbose_name='exercise day')),
                ('finish_num', models.IntegerField(default=0)),
            ],
        ),
    ]
