# Generated by Django 3.2.8 on 2021-10-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icourse',
            name='today',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='icourse',
            name='watched',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pushup',
            name='today',
            field=models.CharField(max_length=8),
        ),
    ]
