# Generated by Django 3.2.8 on 2021-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20211025_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='icourse',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icourse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pushup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
